version: "3.9"

services:
  api:
    build:
      context: services/api
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      API_PORT: ${API_PORT:-8000}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${API_PORT:-8000}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  worker:
    build:
      context: services/worker
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      WORKER_PORT: ${WORKER_PORT:-8001}
    ports:
      - "${WORKER_PORT:-8001}:${WORKER_PORT:-8001}"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${WORKER_PORT:-8001}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
